---
- name: Insert Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: "{{ grafana__system_user }}"
    group: "{{ grafana__system_group }}"
    mode: 0640

- name: Make sure a Grafana container is running
  import_tasks: run_docker.yml

- name: Add datasources
  import_tasks: datasources.yml

- name: Add dashboards
  import_tasks: dashboards.yml
