---
- name: Insert Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: "{{ grafana__system_user }}"
    group: "{{ grafana__system_group }}"
    mode: 0640
  notify: "grafana restart"

- name: Flush handlers in case config was changed(e.g. ip bind)
  meta: flush_handlers

- name: Make sure Grafana is started to config it via api
  service:
    name: grafana-server
    state: started
  become: true

- name: Add datasources
  import_tasks: datasources.yml

- name: Add dashboards
  import_tasks: dashboards.yml
