---
- name: Include install
  import_tasks: install.yml
  tags:
    - grafana
    - grafana::install

- name: Include Configure
  import_tasks: configure.yml
  tags:
    - grafana
    - grafana::configure

- name: Make sure Grafana is enabled and running
  service:
    name: grafana-server
    enabled: true
    state: started
  become: true
  tags:
    - grafana
    - grafana::started
    - grafana::enabled
