---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/cluster/requirements.yml
    ignore-errors: true


driver:
  name: vagrant
  provider:
    name: libvirt


lint:
  name: yamllint
  options:
    config-file: molecule/shared/.yaml_lint.yml


platforms:
  # https://app.vagrantup.com/boxes/search?provider=libvirt
  - name: "${ROLE_CI_PREFIX:-l}-centos7-grafana"
    box: centos/7
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
    provider_options:
      memory: 1024
      cpus: 1
      uri: "'qemu:///system'"
    groups:
      - centos
      - grafana

  - name: "${ROLE_CI_PREFIX:-l}-centos7-influx"
    box: centos/7
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
    provider_options:
      memory: 1024
      cpus: 1
      uri: "'qemu:///system'"
    groups:
      - centos
      - influxdb


provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../shared/cluster/playbook.yml
  config_options:
    defaults:
      log_path: "${CLONE_DIR:-.}/ansible.log"
      stdout_callback: debug
      verbosity: 3
    diff:
      always: true
  inventory:
    links:
      group_vars: ../shared/cluster/group_vars/
  lint:
    name: ansible-lint


scenario:
  name: libvirt-cluster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy


verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
