---
- name: Apt update
  hosts: ubuntu
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: true
      changed_when: false

- name: This_play
  hosts: all
  become: true
  roles:
    - role: zerodowntime.grafana
