{
 "title": "InfluxDB_Internals",
 "description": "InfluxDB internal metrics display",
 "tags": [
  "internal",
  "influxdb",
  "icinga"
 ],
 "time": { "to": "now", "from": "now-24h" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "custom_interval",
    "query": "30s,60s,90s,2m,5m,10m,30m,1h,6h,12h,1d,7d"
   }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "InfluxDB Average Requests",
   "type": "graph",
   "gridPos": { "y": 1, "h": 9, "w": 8, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "httpd",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "req" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "non_negative_derivative", "params": [ "1s" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Writer",
   "type": "graph",
   "gridPos": { "y": 1, "h": 9, "w": 9, "x": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "monitoring.o.veritrack.io", "key": "hostname" },
      { "operator": "=~", "value": "/^influxdbwriter*/", "key": "metric", "condition": "AND" }
     ],
     "alias": "$tag_metric",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "measurement": "icinga",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "tag", "params": [ "metric" ] },
      { "type": "fill", "params": [ "none" ] }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Average Request Duration",
   "type": "graph",
   "gridPos": { "y": 1, "h": 9, "w": 7, "x": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "measurement": "httpd",
     "select": [
      [
       { "type": "field", "params": [ "reqDurationNs" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "non_negative_derivative", "params": [ "1s" ] }
      ]
     ],
     "query": "SELECT non_negative_derivative(mean(\"queryDurationNs\"), 10m) FROM \"queryExecutor\" WHERE $timeFilter GROUP BY time($custom_interval) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  { "title": "MEMORY", "type": "row", "gridPos": { "y": 10, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "InfluxDB Data Caching Composition",
   "type": "table",
   "gridPos": { "y": 11, "h": 13, "w": 8, "x": 0 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "ip-10-10-7-5.ec2.internal", "key": "hostname" }
     ],
     "measurement": "tsm1_cache",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "0" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "diskBytes" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "diskBytes" ] }
      ],
      [
       { "type": "field", "params": [ "memBytes" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "memBytes" ] }
      ],
      [
       { "type": "field", "params": [ "cachedBytes" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "cachedBytes" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Heap Usage : stats-node-0",
   "type": "graph",
   "gridPos": { "y": 11, "h": 13, "w": 16, "x": 8 },
   "yaxes": [
    { "format": "bytes", "label": "MB" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "ip-10-10-7-5.ec2.internal", "key": "hostname" }
     ],
     "alias": "$col",
     "select": [
      [
       { "type": "field", "params": [ "HeapInUse" ] },
       {
        "type": "mean",
        "params": []
       },
       {
        "type": "moving_average",
        "params": [
         10
        ]
       },
       { "type": "alias", "params": [ "heap active" ] }
      ],
      [
       { "type": "field", "params": [ "HeapIdle" ] },
       {
        "type": "mean",
        "params": []
       },
       {
        "type": "moving_average",
        "params": [
         10
        ]
       },
       { "type": "alias", "params": [ "heap idle" ] }
      ]
     ],
     "measurement": "runtime",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "fill", "params": [ "none" ] }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "y": 24, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "y": 25, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "queryReq",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($custom_interval), \"host\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    },
    {
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($custom_interval) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$custom_interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "y": 25, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT non_negative_derivative(last(\"clientError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($custom_interval), \"host\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    },
    {
     "alias": "Server Errors",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT non_negative_derivative(last(\"serverError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($custom_interval), \"host\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "y": 32, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Point Intake",
   "type": "graph",
   "gridPos": { "y": 33, "h": 7, "w": 8, "x": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($custom_interval), \"host\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    },
    {
     "alias": "Write OK",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($custom_interval), \"host\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Measurement Count",
   "type": "singlestat",
   "gridPos": { "y": 33, "h": 7, "w": 8, "x": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT mean(\"numMeasurements\") FROM \"database\" WHERE $timeFilter GROUP BY time($custom_interval) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Series Count",
   "type": "singlestat",
   "gridPos": { "y": 33, "h": 7, "w": 8, "x": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "query": "SELECT mean(\"numSeries\") FROM \"database\" WHERE $timeFilter GROUP BY time($custom_interval) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  }
 ]
}